'use client';

import {
  FaArrowLeft,
  FaBlog,
  FaBolt,
  FaBookOpen,
  FaBriefcase,
  FaCalendarAlt,
  FaChartLine,
  FaChartPie,
  FaCheck,
  FaCheckCircle,
  FaChevronDown,
  FaChevronLeft,
  FaChevronRight,
  FaCircle,
  FaClock,
  FaCloudUploadAlt,
  FaCopy,
  FaDownload,
  FaEdit,
  FaExclamationCircle,
  FaExclamationTriangle,
  FaExternalLinkAlt,
  FaEye,
  FaEyeSlash,
  FaCog,
  FaCoins,
  FaFileAlt,
  FaFilePdf,
  FaFilm,
  FaFilter,
  FaFolderOpen,
  FaGlobe,
  FaHistory,
  FaHandHoldingUsd,
  FaImage,
  FaImages,
  FaLink,
  FaList,
  FaMoneyBillWave,
  FaMinus,
  FaPen,
  FaPlus,
  FaPlusCircle,
  FaPhotoVideo,
  FaProjectDiagram,
  FaQuestionCircle,
  FaRedoAlt,
  FaSave,
  FaSearch,
  FaShieldAlt,
  FaSignOutAlt,
  FaSpinner,
  FaSyncAlt,
  FaTachometerAlt,
  FaTh,
  FaTimes,
  FaTrash,
  FaUniversity,
  FaUpload,
  FaUserPlus,
  FaUsers,
} from 'react-icons/fa';

const ICON_MAP = {
  'arrow-left': FaArrowLeft,
  blog: FaBlog,
  bolt: FaBolt,
  'book-open': FaBookOpen,
  briefcase: FaBriefcase,
  calendar: FaCalendarAlt,
  'chart-line': FaChartLine,
  'chart-pie': FaChartPie,
  check: FaCheck,
  'check-circle': FaCheckCircle,
  'chevron-down': FaChevronDown,
  'chevron-left': FaChevronLeft,
  'chevron-right': FaChevronRight,
  circle: FaCircle,
  'circle-exclamation': FaExclamationCircle,
  'circle-question': FaQuestionCircle,
  clock: FaClock,
  'cloud-upload-alt': FaCloudUploadAlt,
  copy: FaCopy,
  download: FaDownload,
  edit: FaEdit,
  'exclamation-circle': FaExclamationCircle,
  'exclamation-triangle': FaExclamationTriangle,
  'external-link-alt': FaExternalLinkAlt,
  eye: FaEye,
  'eye-slash': FaEyeSlash,
  gear: FaCog,
  coins: FaCoins,
  'file-alt': FaFileAlt,
  'file-pdf': FaFilePdf,
  'file-pen': FaPen,
  film: FaFilm,
  filter: FaFilter,
  'folder-open': FaFolderOpen,
  globe: FaGlobe,
  history: FaHistory,
  'hand-holding-usd': FaHandHoldingUsd,
  image: FaImage,
  images: FaImages,
  link: FaLink,
  list: FaList,
  minus: FaMinus,
  'money-bill-transfer': FaMoneyBillWave,
  pen: FaPen,
  plus: FaPlus,
  'plus-circle': FaPlusCircle,
  'photo-film': FaPhotoVideo,
  'diagram-project': FaProjectDiagram,
  'rotate-left': FaRedoAlt,
  save: FaSave,
  search: FaSearch,
  'shield-alt': FaShieldAlt,
  'sign-out-alt': FaSignOutAlt,
  spinner: FaSpinner,
  'sync-alt': FaSyncAlt,
  'tachometer-alt': FaTachometerAlt,
  th: FaTh,
  times: FaTimes,
  trash: FaTrash,
  'undo-alt': FaRedoAlt,
  university: FaUniversity,
  upload: FaUpload,
  'user-cog': FaCog,
  'user-plus': FaUserPlus,
  users: FaUsers,
};

export default function Icon({ className = '', ...props }) {
  const classes = String(className).trim().split(/\s+/).filter(Boolean);
  const faToken = classes.find((c) => c.startsWith('fa-') && c !== 'fa-spin');
  const iconName = faToken ? faToken.replace(/^fa-/, '') : 'circle';
  const Comp = ICON_MAP[iconName] || FaCircle;

  const isSpin = classes.includes('fa-spin');
  const filtered = classes.filter((c) => c !== 'fas' && c !== 'far' && c !== 'fab' && c !== 'fa' && !c.startsWith('fa-') && c !== 'fa-spin');
  const finalClassName = [isSpin ? 'animate-spin' : '', ...filtered].filter(Boolean).join(' ');

  return <Comp className={finalClassName} aria-hidden="true" {...props} />;
}
